# Generated by Django 2.2.2 on 2021-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_f_name', models.TextField()),
                ('friend_l_name', models.TextField()),
                ('friend_number', models.TextField(null=True)),
                ('friend_email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
